### ISSUE TITLE
Getting median fluorescence intensity (MFI) values and its quartile values from a specific channel

### ISSUE THREAD

**Issue by mikejiang** [RGLab/cytoUtils#1]
close RGLab/flowWorkspace#212

Let's move the conversations here since we want to only keep the core infrastructural APIs at `flowWorkspace` and add the new peripheral helper functions in `cytoUtils` to ensure the former is stable.

@gfinak brought up an interesting idea of a general purpose API for computing population stats. I think it is worth to experiment to see how it works.

**Comment by mikejiang** [comment]
@cjungR, @gfinak See the new [getStats](https://github.com/RGLab/cytoUtils/blob/master/R/getStats.R#L20-L38)

**Comment by cjungR** [comment]
Hi,

First of all thank you for all your help! I'd like to try ```getStats``` but I'm getting the following error when trying to install ```cytoUtils```: 

```
> install_github("RGLab/cytoUtils")
Downloading GitHub repo RGLab/cytoUtils@master
from URL https://api.github.com/repos/RGLab/cytoUtils/zipball/master
Installing cytoUtils
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL "C:/Users/cham/AppData/Local/Temp/RtmpG42Elu/devtools2a886dea50dd/RGLab-cytoUtils-d47d69a"  \
  --library="C:/Users/cham/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'cytoUtils' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
C:/RBuildTools/3.4/mingw_32/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG -DROUT -I//i386/include/libxml2 -I//i386/include -DLIBXML_STATIC   -I"C:/Users/cham/Documents/R/win-library/3.3/Rcpp/include" -I"C:/Users/cham/Documents/R/win-library/3.3/flowWorkspace/include" -I"C:/Users/cham/Documents/R/win-library/3.3/BH/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
cytoUtils_types.h:1:39: fatal error: flowWorkspace/GatingSet.hpp: No such file or directory
 #include <flowWorkspace/GatingSet.hpp>
                                       ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="cytoUtils.dll" OBJECTS="RcppExports.o getDescendants.o"' had status 2
ERROR: compilation failed for package 'cytoUtils'
* removing 'C:/Users/cham/Documents/R/win-library/3.3/cytoUtils'
Error: Command failed (1)
```

Is there something I need to do manually to install this package? Thanks!

**Comment by mikejiang** [comment]
you need the dev version of `flowWorkspace` from github

**Comment by mehrnoushmalek** [comment]
Hello Mike,

I get similar error for installing cytoUtils. flowWorkspace version 3.27.11, flowCore 1.45.4.

`getDescendants.cpp: In function ‘VertexID_vec getDescendants(Rcpp::XPtr<GatingSet>, std::__cxx11::string, std::__cxx11::string)’:
getDescendants.cpp:35:62: error: cannot convert ‘GatingHierarchy’ to ‘GatingHierarchy*’ in initialization
   GatingHierarchy * gh = gsPtr->getGatingHierarchy(sampleName);
                                                              ^
/usr/lib/R/etc/Makeconf:168: recipe for target 'getDescendants.o' failed
make: *** [getDescendants.o] Error 1
ERROR: compilation failed for package ‘cytoUtils’
* removing ‘/home/mmalekes/R/x86_64-pc-linux-gnu-library/3.4/cytoUtils’
Installation failed: Command failed (1)`

**Comment by mikejiang** [comment]
try again

**Comment by mehrnoushmalek** [comment]
It worked, thanks!

**Comment by mehrnoushmalek** [comment]
Hello Mike,

Hope you're doing well. I was wondering if there's a way to calculate the raw MFI for  some specific markers for a node?
As an example let's say I want to calculate CD27 MFI on CD4+CD8+ cells, but not on the transformed data. 
`getStats(gs, nodes="CD4+CD8+",type = pop.MFI)` give me the MFI of all markers including CD27, but based on the transformed data (e.g. returning MFI of 1.12 instead of 607 for CD27).

Let me know if you want me to open a new issue.

Best,

**Comment by cjungR** [comment]
By chance I actually came on to post the exact same question as @mehrnoushmalek - would love to hear your thoughts as well @mikejiang

**Comment by mikejiang** [comment]
See https://github.com/RGLab/cytoUtils/blob/master/R/getStats.R#L37-L38

**Comment by mehrnoushmalek** [comment]
Thank you Mike!

**Comment by cjungR** [comment]
Hi Mike,

Thank you for your help as always! This works great if you used a built-in function to transform data, but how about if a custom function was used? I used the following: 

```
transformx <- function(x) {
  markers <- colnames(x)
  x <- x[, markers]
  lgcl <- logicleTransform(w=0.25, t=16409, m=4.5, a=0)
  logicle_transform <- transformList(markers, lgcl)
  x <- transform(x,logicle_transform)
  
  
  return(x)
}
```

`getTransformations(gs[[1]])` with transformed data returns `list()`, resulting in the following error with `getStats`:

```
Error in FUN(X[[i]], ...) : 
  No inverse transformation is found from the GatingSet!
```

Do you have any ideas on how I could work around this? Thank you.

**Comment by cjungR** [comment]
Seems like the way to do it is to use `logicle_trans`
```
ncdf <- read.ncdfFlowSet("UN.fcs")
gs <- GatingSet(ncdf)

chnls <- colnames(gs)
lgcl <- logicle_trans(w=0.25, t=16409, m=4.5, a=0)
trans <- transformerList(chnls, lgcl)
gs <- transform(gs, trans)
```
Transforming a `GatingSet` allows for `getStats(gs, nodes, type = pop.MFI, inverse.transform = TRUE)` to work. 

I was then able to reproduce the gating and also get the MFI values. Setting `raw.scale = FALSE` on `plotGate` allowed me to see the same tick marks as before.

**Comment by mikejiang** [comment]
@cjungR , 
>This works great if you used a built-in function to transform data, but how about if a custom function was used? 

No, `inverse.transform` flag works for any `stats` function (both built-in and custom)

>getTransformations(gs[[1]]) with transformed data returns list(),Do you have any ideas on how I could work around this?

As you've already figured out, `GatingSet` has to be the one that was transformed by a `transformerList` in order to for inverse transforming to work

>Seems like the way to do it is to use logicle_trans

No. Any transformation function would do as long as they can be wrapped in `transformerList` and then applied to `GatingSet`

**Comment by cjungR** [comment]
Got it, yes I meant `logicle_trans` for my particular case.
