### ISSUE TITLE
Installation depends on `TreeSummarizedExperiment`

### ISSUE THREAD

**Issue by MiguelRodo** [RGLab/cytoUtils#4]
Hi

I tried installing the package from GitHub on Ubuntu, but got the following error along the way:
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘TreeSummarizedExperiment’
```

Installing `TreeSummarizedExperiment` allowed then allowed installation to succeed

**Comment by mikejiang** [comment]
Thank you for reporting bug. Just updated DESCRIPTION.
